apiVersion: "tinkerbell.org/v1alpha1"
kind: Hardware
metadata:
  name: elite8200
  namespace: tink-system
spec:
  disks:
    - device: /dev/sda
  metadata:
    facility:
      facility_code: onprem
    manufacturer:
      slug: hp
    instance:
      userdata: ""
      hostname: "elite8200-1"
      id: "e8:39:35:5c:e4:81"
      operating_system:
        distro: "ubuntu"
        os_slug: "ubuntu_22_04"
        version: "22.04"
  interfaces:
    - dhcp:
        arch: x86_64
        hostname: elite8200-1
        ip:
          address: 192.168.1.71
          gateway: 192.168.1.1
          netmask: 255.255.255.0
        lease_time: 86400
        mac: e8:39:35:5c:e4:81
        name_servers:
          - 192.168.1.12
          - 8.8.8.8
        uefi: false
      netboot:
        allowPXE: true
        allowWorkflow: true